[build.environment]
  NPM_FLAGS = "--version"

[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
  publish = "dist"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- /"

[dev]
  command = "pnpm start"

[[headers]]
  for = "/*"
  [headers.values]
  cache-control=public
  max-age=15552000
